### ISSUE TITLE
Head and Body

### ISSUE THREAD

**Issue by straid13** [ntnyq/gulp-format-html#2]
Hi!
Why there are no indents before tags Head and Body in otput html file? I think they should be there.

As it is:
```
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
</body>
</html>
```

As it should be:
```
<!DOCTYPE html>
<html lang="en">
  <head>
  </head>
  <body>
  </body>
</html>
```

**Comment by ntnyq** [comment]
It's available by passing an  option and setting `indent_inner_html` true.

``` js
gulp
  .src('src/views/**/*.html')
  .pipe(formatHtml({
    indent_inner_html: true
  }))
  .pipe(gulp.dest('dist'))
```
Gulp-format-html uses __js-beautify__ to format html files.

You can check [js-beautify](https://github.com/beautify-web/js-beautify#css--html) for more available options for now.

I'll add the options to README ASAP.

**Comment by straid13** [comment]
Thanks.
